Indexing

In [1]:
import numpy as np

In [5]:
arr_1D = np.array([1,2,3,4,5,6,7,8,9])
arr_2D = np.array([[1,2,3],[4,5,6]])
arr_3D = np.array([[[1,2,3],[4,5,6]], [[6,5,4],[3,2,1]]])

Access

In [8]:
print(arr_1D[3])

print(arr_2D[0,2])

4
3


Slicing - array[start:end:step]

In [10]:
print(arr_1D[:])
print(arr_1D[::])
print(arr_1D[1::])
print(arr_1D[:4:])
print(arr_1D[::2])
print(arr_1D[::-1])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[1 2 3 4]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


Fancy Indexing

In [16]:
print(arr_1D[[0,3,2,5]])

[1 4 3 6]


Boolean mas

In [12]:
print(arr_1D[arr_1D < 5])

[1 2 3 4]


Filtering