Re-shaping

In [1]:
import numpy as np

In [2]:
arr_1D = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
print(arr_1D.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Flattering

In [6]:
barun = np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
print(barun.ravel())
print(barun.flatten())

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
