Array modification

In [2]:
import numpy as np

In [3]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([[1,2,3,4], [5,6,7,8]])

1D

In [4]:
m_array_1 = np.insert(array_1, 2, 200)
print(m_array_1)

[  1   2 200   3   4]


2D

In [5]:
m_array_2 = np.insert(array_2, 0, [1,2, 7, 8], axis=0) # row wise
print(m_array_2)

[[1 2 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [6]:
m_array_2 = np.insert(array_2, 0, [1,2], axis=1) # column wise
print(m_array_2)

[[1 1 2 3 4]
 [2 5 6 7 8]]


In [7]:
m_array_2 = np.insert(array_2, 0, [1,2], axis=None)
print(m_array_2)

[1 2 1 2 3 4 5 6 7 8]


Append

In [8]:
array_3 = np.append(array_2, [1,1,1])
print(array_3)

[1 2 3 4 5 6 7 8 1 1 1]


Concatinate

In [9]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,3,2,1])

In [10]:
carr3 = np.concatenate((arr1, arr2))
carr4 = np.concatenate((arr1, arr2))
print(carr4)

[1 2 3 4 4 3 2 1]


2D

In [11]:
array_3 = np.array([[4,3,2,1], [8,7,6,5]])

In [12]:
carr_5 = np.concatenate((array_2, array_3), axis=1)
print(carr_5)

[[1 2 3 4 4 3 2 1]
 [5 6 7 8 8 7 6 5]]


Stacking

In [19]:
new_array_v = np.vstack((array_2, array_3))
new_array_h = np.hstack((array_2,array_3))
print(new_array_v)
print(new_array_h)

[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]
[[1 2 3 4 4 3 2 1]
 [5 6 7 8 8 7 6 5]]


Splitting

In [25]:
s_new_a = np.split(array_1, 2)
print(s_new_a)

[array([1, 2]), array([3, 4])]


In [29]:
s_new_a_v = np.vsplit(array_2, 2)
print(s_new_a_v)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [31]:
s_new_a_h = np.hsplit(array_2, 1)
print(s_new_a_h)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]])]
