Handle missing value and Spelcial case

In [1]:
import numpy as np

In [9]:
array = np.array([1,2, np.nan ,4, np.nan])

In [11]:
print(np.isnan(array))


[False False  True False  True]


replace this missing value by defult value

In [12]:
clean_arr = np.nan_to_num(array)
print(clean_arr)

[1. 2. 0. 4. 0.]


use specific value

In [23]:
array1 = np.array([1,2, np.nan ,4, np.nan])

In [24]:
clean = np.nan_to_num(array1, nan=5)
print(clean)

[1. 2. 5. 4. 5.]


For infinite

In [27]:
array2 = np.array([1,2, np.inf ,4, -np.inf])

In [28]:
clean_inf = np.nan_to_num(array2, posinf=222, neginf=333)
print(clean_inf)

[  1.   2. 222.   4. 333.]
